# Generated by Django 2.2 on 2019-04-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcodelookup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40)),
                ('cover', models.TextField(default='https://i.ibb.co/dj1qb0D/product-image-not-found.gif')),
                ('no_of_pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=120)),
                ('publish_data', models.CharField(max_length=40)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='barcodelookup.Product')),
            ],
        ),
    ]
